// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates personalized reinforcement text using AI to encourage users to explore the website further and increase conversion rate.
 *
 * - generateReinforcementText - A function that generates personalized reinforcement text based on user behavior data.
 * - GenerateReinforcementTextInput - The input type for the generateReinforcementText function.
 * - GenerateReinforcementTextOutput - The return type for the generateReinforcementText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateReinforcementTextInputSchema = z.object({
  userBehaviorData: z
    .string()
    .describe(
      'A string containing the user behavior data, such as pages visited, time spent on site, and actions taken.'
    ),
});
export type GenerateReinforcementTextInput = z.infer<
  typeof GenerateReinforcementTextInputSchema
>;

const GenerateReinforcementTextOutputSchema = z.object({
  reinforcementText: z
    .string()
    .describe(
      'Personalized reinforcement text to encourage users to explore the website further.'
    ),
});
export type GenerateReinforcementTextOutput = z.infer<
  typeof GenerateReinforcementTextOutputSchema
>;

export async function generateReinforcementText(
  input: GenerateReinforcementTextInput
): Promise<GenerateReinforcementTextOutput> {
  return generateReinforcementTextFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateReinforcementTextPrompt',
  input: {schema: GenerateReinforcementTextInputSchema},
  output: {schema: GenerateReinforcementTextOutputSchema},
  prompt: `You are an AI assistant designed to generate personalized reinforcement text to encourage users to explore a website further.

  Based on the following user behavior data, generate a short, engaging message to encourage the user to explore the website further, increasing the conversion rate.

  User Behavior Data: {{{userBehaviorData}}}

  Reinforcement Text:`, // Ensure the prompt is well-formatted and includes clear instructions.
});

const generateReinforcementTextFlow = ai.defineFlow(
  {
    name: 'generateReinforcementTextFlow',
    inputSchema: GenerateReinforcementTextInputSchema,
    outputSchema: GenerateReinforcementTextOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
